export const STEP_ACTION = {
  SELECCIONAR_ZONA_BATALLA: 'SELECCIONAR ZONA BATALLA',
  CAMBIAR_POSICION: 'CAMBIAR POSICION',
  ATACAR_CARTA: 'ATACAR CARTA',
  ATACAR_CARTA_SELECCIONAR_ZB_ENEMIGA: 'ATACAR CARTA SELECCIONAR ZB ENEMIGA',
  SELECCIONAR_MANO: 'SELECCIONAR MANO',
  COLOCAR_CARTA: 'COLOCAR CARTA',
  COLOCAR_SELECCIONAR_ZONA_BATALLA: 'COLOCAR SELECCIONAR ZONA BATALLA',
  STAND_BY: 'STAND BY'
}
